CREATE SEQUENCE IF NOT EXISTS doctor_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE doctor
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cep          VARCHAR(255),
    city         VARCHAR(255),
    complement   VARCHAR(255),
    neighborhood VARCHAR(255),
    number       VARCHAR(255),
    street       VARCHAR(255),
    uf           VARCHAR(255),
    crm          VARCHAR(255),
    email        VARCHAR(255),
    name         VARCHAR(255),
    specialty    VARCHAR(255),
    CONSTRAINT doctor_pkey PRIMARY KEY (id)
);