CREATE TABLE patient
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    cpf          VARCHAR(255),
    phone        VARCHAR(255),
    active       BOOLEAN,
    street       VARCHAR(255),
    neighborhood VARCHAR(255),
    cep          VARCHAR(255),
    city         VARCHAR(255),
    uf           VARCHAR(255),
    number       VARCHAR(255),
    complement   VARCHAR(255),
    CONSTRAINT pk_patient PRIMARY KEY (id)
);

DROP SEQUENCE chat_seq CASCADE;

DROP SEQUENCE doctor_id_seq CASCADE;

DROP SEQUENCE message_seq CASCADE;